[package]
name = "chat-thang-server"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]

[dependencies]
ws = "*"
log = "*"
env_logger = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
